language: go

go:
- 1.8.x

before_install:
- echo "***** Install glide *****"
- curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o glide.tar.gz
- mkdir -p $HOME/bin
- tar -vxz -C $HOME/bin --strip=1 -f glide.tar.gz
- export PATH="$HOME/bin:$PATH"
- echo "***** Install Node.js *****"
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- "(cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)"
- source ~/.nvm/nvm.sh
- nvm install 6

install:
- make deps webpack bindata

script:
- make test
- make build

before_deploy:
- sudo apt-get install -y rpm
- make build

deploy:
  provider: releases
  api_key:
    secure: rD95ga76FnRORmYyZZPoA5jwkweVXNs75/d8wmFEmbhk7dO1trnIohgcVtRmO2yjOJwLJCMVOan5I7UZswq8n3Bb/koOBcux1aRuQB4H1DkCd8hd3Ts0QlcN3pfS6UUNezPlcJn2iX6qMcBN1gjA1YV/PbmhdQkbHIluIrzjbG6mOZmYdH/SJqFm9VtHXAM42TU44MKBhNdirgl0oTQjiCih9fd2zEfIrSqZ+1WAvxu2jwa2yH67LFzLD6VwTI3aCWhXefHg+m0o/KkePg+wyoYRFa6Zmb93NO4/yNdgm4AIwcaTowStykBfi1RZcLSyp0j++Ao42SW/cxKSZPJ2FAnN+8QGTZd/KPoKrvhRhFIrPkf4I8tTo3q8QPe3P9L03tBlOJd5MjS9vShzNtPUZFLYNwljJrYn4QzXQXdSzl/wueISkGqCSJVfb9TxVYStzYS7fUMQ7okk73DbESdO1p9ZgkT9RxyMlsjfc91uoI4gJwPtIh0mro5OpA2ySxBVDBgXrzpgGyDkVDl9pYcoZYchdt+Vz2IEaoG0PTSVgT7eLDPaNdapCCuuw805VbxwjZ4KLdXcGQGpXA3APIpDMhiTziwSHh4AcTzfiQHOs28bcDrw4R/db6k3q1oPsOA2lkzFuvGsib3ALhS4Oh5I/hN9ozq9WBqDj1yC6TA2WhY=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: umatoma/trunks
