language: go

go:
  - 1.8.x

before_install:
  - curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o glide.tar.gz
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide.tar.gz
  - export PATH="$HOME/bin:$PATH"

install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u github.com/elazarl/go-bindata-assetfs/...
  - go get -u github.com/golang/lint/golint
  - glide install
