language: go

go:
  - 1.8.x

before_install:
  - curl https://glide.sh/get | sh

install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u github.com/elazarl/go-bindata-assetfs/...
  - go get -u github.com/golang/lint/golint
